Release1.1
tests-always-included/ddq-backend-mysql pull request #3
Opened 2016-10-31 16:37 UTC by lnagle93

2016-10-31 16:52 UTC, GoogilyBoogily commented on package.json
> +    "version": "1.0.1",
These changes aren't backwards compatible. So the version bump isn't correct.

2016-10-31 17:11 UTC, fidian requested changes

2016-10-31 17:11 UTC, fidian commented on lib/ddq-backend-mysql.js
> +
Was this accidental?

2016-10-31 17:11 UTC, fidian commented on lib/ddq-backend-mysql.js
> +        stopListening(callback) {
This function, due to a race condition, can complete and call the callback.  After successfully `stopListening` the ddq core could get an event with a wrapped message.

To close this hole, you'll have to wrap the emit in a condition checking if you are still polling.  But I don't like that solution.  I would rather have stopListening stall until we know it is certainly stopped, especially if we intend to close the connection as well.  ... Thinking.

2016-10-31 17:29 UTC, lnagle93 commented on lib/ddq-backend-mysql.js
> +
Yes; removed.

2016-10-31 17:30 UTC, lnagle93 commented on package.json
> +    "version": "1.0.1",
Fixed.

2016-11-01 20:23 UTC, AbsentSemicolon commented
Looks good to me though we need to figure out why the tests are failing in Travis.

2016-11-01 22:07 UTC, GoogilyBoogily commented
Looks solid.

2016-11-03 12:51 UTC, fidian requested changes

2016-11-03 12:51 UTC, fidian commented on lib/ddq-backend-mysql.js
> +        stopListening(callback) {
We talked a bit about this.  I think I'll discuss it more with you, but the essence of the solution is to, I believe, track a few more things in DDQ and pull more logic out of the plugins.  Let DDQ coordinate the callbacks for starting/stopping/etc.  The plugin shouldn't even worry about `this.currentlyRestoring` nor `this.currentlyPolling` in the way it's currently approaching that problem.  It should track when it is doing an operation, but probably not when it is stalling.

2016-12-15 16:17 UTC, closed without merging