Release2.0
tests-always-included/ddq-backend-mysql pull request #4
Opened 2016-12-15 16:15 UTC by lnagle93

2016-12-15 16:58 UTC, AbsentSemicolon commented on script/test-race-conditions.spec.js
> +        return;
Do we need a return here if we call the callback? Don't remember how that works.

2016-12-15 17:01 UTC, AbsentSemicolon commented on script/test-race-conditions.spec.js
> + * Example: methodFails("nameOfMethod", "param1", "param2", "param3");
Should use JsDoc to denote example.

http://usejsdoc.org/tags-example.html

2016-12-15 17:04 UTC, AbsentSemicolon commented on script/test-race-conditions.spec.js
> + * Example: methodSucceeds("nameOfMethod", "param1", "param2", "param3");
JsDoc @example here as well and look for other example areas.

2016-12-15 17:05 UTC, AbsentSemicolon commented on script/test-race-conditions.spec.js
> + * Calls a list of methods one after another. This is used for testing that
dont need that

2016-12-15 17:05 UTC, AbsentSemicolon commented on script/test-race-conditions.spec.js
> + * Example:
@example

2016-12-15 17:06 UTC, AbsentSemicolon commented on script/test-race-conditions.spec.js
> +    spyOn(instance, "close").andCallThrough();
I believe `.andCallThrough()` is the default so you shouldn't need to include it for these.

2016-12-15 17:07 UTC, AbsentSemicolon commented on script/test-race-conditions.spec.js
> +            expect(instance.backend.connection).not.toBeUndefined();
You could just use `.toBeDefined()`

2016-12-15 17:11 UTC, AbsentSemicolon commented on spec/lib/ddq-backend-mysql.spec.js
> +    describe(".startListeninging()", () => {
Think this should be `.startListening()`

2016-12-15 17:19 UTC, lnagle93 commented on script/test-race-conditions.spec.js
> + * Example: methodFails("nameOfMethod", "param1", "param2", "param3");
Didn't know about that, thanks. Fixed.

2016-12-15 17:19 UTC, lnagle93 commented on script/test-race-conditions.spec.js
> +        return;
It is needed to prevent the code below the if block from running.

2016-12-15 17:19 UTC, lnagle93 commented on script/test-race-conditions.spec.js
> + * Example: methodSucceeds("nameOfMethod", "param1", "param2", "param3");
Fixed.

2016-12-15 17:36 UTC, lnagle commented on script/test-race-conditions.spec.js
> + * Calls a list of methods one after another. This is used for testing that
Fixed.

2016-12-15 17:42 UTC, lnagle93 commented on script/test-race-conditions.spec.js
> + * Example:
Fixed.

2016-12-15 17:43 UTC, lnagle commented on script/test-race-conditions.spec.js
> +    spyOn(instance, "close").andCallThrough();
Pretty sure you're wrong. `spyOn` and `createSpy` both make functions that are effectively noops with counters.

2016-12-15 17:45 UTC, lnagle93 commented on script/test-race-conditions.spec.js
> +            expect(instance.backend.connection).not.toBeUndefined();
Fixed.

2016-12-15 17:45 UTC, lnagle93 commented on spec/lib/ddq-backend-mysql.spec.js
> +    describe(".startListeninging()", () => {
Fixed.

2016-12-15 18:23 UTC, AbsentSemicolon commented on script/test-race-conditions.spec.js
> +    spyOn(instance, "close").andCallThrough();
Looks like something that talked about but not implemented in 1.3 at least.

2016-12-15 18:23 UTC, AbsentSemicolon commented on script/test-race-conditions.spec.js
> +        return;
Excellent, just wondering.

2016-12-15 18:25 UTC, AbsentSemicolon commented
Looks good, approved.

2017-01-02 16:31 UTC, fidian requested changes

2017-01-02 16:31 UTC, fidian commented on package.json
> +        "ddq": "2.0.0",
This creates a circular dependency.  You should list this under `peerDependencies`.  https://nodejs.org/en/blog/npm/peer-dependencies/

2017-01-04 20:01 UTC, quantumew commented on package.json
> +        "ddq": "2.0.0",
Fixed that. The build will fail though until DDQ is published. Tests are passing locally. My commits 
46eee4607d09d2f88ca247764e170ef043da943b
fb9ac39046289a652a13be072a4d0939a129ed38

2017-01-05 15:50 UTC, fidian requested changes
Need one thing changed and there's one really weird thing I don't understand.

2017-01-05 15:50 UTC, fidian commented on spec/lib/ddq-backend-mysql.spec.js
> +                }, {});
Why does the callback take two arguments?

2017-01-05 15:50 UTC, fidian commented on spec/lib/ddq-backend-mysql.spec.js
> +                instance.sendMessage("Example Message", null, () => {});
This should work with and without the `null`.

    instance.sendMessage("Example Message", null, () => {});
    instance.sendMessage("Example Message", () => {});

2017-01-05 16:37 UTC, quantumew commented on spec/lib/ddq-backend-mysql.spec.js
> +                }, {});
My mistake 0633ddef4d1696db618d318cc32312f7d6db5960

2017-01-05 16:37 UTC, quantumew commented on spec/lib/ddq-backend-mysql.spec.js
> +                instance.sendMessage("Example Message", null, () => {});
4fe18a097a56af6629bbcf5033de13677b7aec7f

2017-01-05 19:38 UTC, quantumew commented
@fidian reverted the topic stuff and added an extra check before checking data.affectedRows so we can remove the empty object from the tests. I see now that was why that was added. 8d914e232f2a7bd04e0ea9483e34b626a0937c09

2017-01-05 19:39 UTC, fidian commented
Awesome.  Thanks @lnagle93 and @quantumew for your hard work!

2017-01-05 19:40 UTC, fidian commented
Can't merge this until tests pass.  :-(

2017-01-09 20:57 UTC, quantumew commented on package.json
> +        "ddq-backend-tests": "git://github.com/tests-always-included/ddq-backend-tests.git#initial",
This is temporary until this is published to get build to pass.

2017-01-10 20:08 UTC, fidian requested changes

2017-01-10 20:08 UTC, fidian commented on package.json
> +        "ddq-backend-tests": "git://github.com/tests-always-included/ddq-backend-tests.git#initial",
We shouldn't publish this until the backend tests are published.

2017-01-20 19:48 UTC, quantumew commented
@fidian Here are the plugin bug fixes 0d0ae557415c6f304879562767060f3be0af6dda

Note to reviewers, the package.json is shimmed to point to a branch on ddq-backend-tests to get the tests passing until they are published.

2017-01-23 20:17 UTC, kyle-long commented
I think we should be careful about the phrase "cleaned up". We use it multiple contexts and sometimes in makes little sense to me. For example...

```
        /**
         * Queries for jobs that have stopped, and primes them to be cleaned up.
         */
        function heartbeatCleanup() {
```

Is it "cleaning up" those records or is it making them consumable again? The record still exist.

2017-01-24 14:32 UTC, kyle-long commented
Can't comment on the line because it is not in the diff.

If "remove" is call but the "requeued" column is set to true, it will not call "requeue" in order to set "requeued" to false. Instead nothing will happen.

This is based off of the assumption that a DELETE will not error if it finds no records to delete.

2017-01-24 14:36 UTC, kyle-long commented
I think the last thing I noticed was if "requeue" was called after the heartbeat expired for that message and a new listener had picked it up it would remove the ability for the new listener to remove that message and instead it would get processed an additional time.

I am not sure how much we care about this one.

2017-01-24 14:39 UTC, kyle-long requested changes

2017-01-24 14:39 UTC, kyle-long commented on lib/ddq-backend-mysql.js
>              cycleCounter = 0;
FUNCTIONAL?

sending messages could be done asynchronously. The counter really should be on a per message basis instead of on a module level. For that matter, you could have multiple listeners potentially listening to different topics.

However, how much do we care? The worse that could happen is that it gets stuck in an infinite loop trying to insert the messages if they come in PERFECTLY. The mostly likely scenario nothing happens at all.

2017-01-24 19:58 UTC, quantumew commented on lib/ddq-backend-mysql.js
>              cycleCounter = 0;
Fixed

2017-01-26 14:59 UTC, quantumew commented
@kyle-long here are the code review fixes and such 5f28dc90b23f091418f270eeaf79cb0df5af4b43

2017-01-26 15:25 UTC, kyle-long requested changes

2017-01-26 15:25 UTC, kyle-long commented on lib/ddq-backend-mysql.js
> +            SET heartbeatDate = NOW(3)
I see, so this makes it more precise for the deadlocking. Could you add a comment about this? After a quick google I couldn't find it here http://www.w3schools.com/sqL/func_now.asp and didn't figure it out until I tested it.

Makes sense though

2017-01-26 15:25 UTC, kyle-long commented on script/mysql-commands.sql
> +    index isProcessing(isProcessing),
Why lowercase? I like uppercase and we do it for the rest of the stuff.

2017-01-26 15:46 UTC, fidian commented on script/mysql-commands.sql
> +    index isProcessing(isProcessing),
Should be uppercase. https://tests-always-included.github.io/style-guide/lang/sql/
Looks like the SQL guide isn't linked up.  I'll go fix that.

2017-01-26 15:48 UTC, quantumew commented on script/mysql-commands.sql
> +    index isProcessing(isProcessing),
Yea, sorry that was not intentional. Fixed

2017-01-26 15:48 UTC, quantumew commented on lib/ddq-backend-mysql.js
> +            SET heartbeatDate = NOW(3)
Oh yea good call. Note added.

2017-01-26 16:24 UTC, kyle-long commented
In those comments I wanted a bit about why we want the time to be more accurate right? Thats because of the deadlocking issue right?

2017-01-26 18:36 UTC, kyle-long approved these changes

2017-01-27 15:44 UTC, kyle-long approved these changes

2017-01-27 17:34 UTC, merged